# Basics of NumPy Arrays

## Topics
- Attributes of NumPy Arrays 
- Indexing of NumPy Arrays 
- Slicing of NumPy Arrays
- Reshaping NumPy Arrays 
- Concatenating of NumPy Arrays
- Splitting of NumPy Arrays

## Import NumPy

In [17]:
import numpy as np

## A. Attributes of NumPy Array
- `ndim` - gives the dimensions of each array
- `shape` - gives the shape of each array as a tuple 
- `size` - gives the total number of elements in the array
- `dtype` - gives the data type of the array

In [18]:
# contruct an array
array_int_1D = np.random.randint(low=2, high=20, size=6) # 1 dimensional
array_int_2D = np.random.randint(low=2, high=20, size=(4,5)) # 2 dimensional
array_int_3D = np.random.randint(low=2, high=20, size=(3,4,5)) # 3 dimensional

# accessing the attributes of the array
print(f"The dimensions are : {array_int_1D.ndim}, {array_int_2D.ndim}, {array_int_3D.ndim}") # gives the dimensions of the three arrays

print(f"The shape are : {array_int_1D.shape}, {array_int_2D.shape}, {array_int_3D.shape}") # gives the shape of the arrays 

print(f"The sizes are : {array_int_1D.size}, {array_int_2D.size}, {array_int_3D.size}") # gives the total number of elements in the array

print(f"The datatypes are : {array_int_1D.dtype}, {array_int_2D.dtype}, {array_int_3D.dtype}") # gives the datatype of the elements of the array

The dimensions are : 1, 2, 3
The shape are : (6,), (4, 5), (3, 4, 5)
The sizes are : 6, 20, 60
The datatypes are : int32, int32, int32


## B. Array Indexing

Let us first take a look at the three arrays we have created. 

In [19]:
print("ARRAY 1")
print(array_int_1D,'\n')

print("ARRAY 2")
print(array_int_2D,'\n')

print("ARRAY 3")
print(array_int_3D)

ARRAY 1
[ 4  5  8  7  7 15] 

ARRAY 2
[[ 3 15 17  2 10]
 [ 6  7 10  5  2]
 [ 3 10  7 15 12]
 [19 16  5 12 14]] 

ARRAY 3
[[[16  8  3 19  7]
  [ 6 14  3  6 11]
  [10  4  8 12  4]
  [14  3 15  5 14]]

 [[11  3 15  9  9]
  [18 18  7 15  6]
  [17  4 13  2  4]
  [ 2 17 10 13 16]]

 [[19  3  7  2 19]
  [ 7  3 13  2 13]
  [10 14 17 10  8]
  [16 15 12 11  6]]]


In [20]:
# indexing arrays

# find the second element of the ARRAY 1
print(f'The second element of the 1 D array stated above is : {array_int_1D[1]}')

# find the element present at posotion (1,2) of the ARRAY 2 (note that indexing starts at 0)
print(f'The (1,2)th element i.e. the element at the intersection of the second row and the 3rd column is : {array_int_2D[1,2]}')

# find the element at position (1,2,0)
print(f'The element at (1,2,0)th position is : {array_int_3D[1,2,0]}')

The second element of the 1 D array stated above is : 5
The (1,2)th element i.e. the element at the intersection of the second row and the 3rd column is : 10
The element at (1,2,0)th position is : 17


## C. Array Slicing

In [21]:
print("ARRAY 1")
print(array_int_1D,'\n')

print("ARRAY 2")
print(array_int_2D,'\n')

print("ARRAY 3")
print(array_int_3D)

ARRAY 1
[ 4  5  8  7  7 15] 

ARRAY 2
[[ 3 15 17  2 10]
 [ 6  7 10  5  2]
 [ 3 10  7 15 12]
 [19 16  5 12 14]] 

ARRAY 3
[[[16  8  3 19  7]
  [ 6 14  3  6 11]
  [10  4  8 12  4]
  [14  3 15  5 14]]

 [[11  3 15  9  9]
  [18 18  7 15  6]
  [17  4 13  2  4]
  [ 2 17 10 13 16]]

 [[19  3  7  2 19]
  [ 7  3 13  2 13]
  [10 14 17 10  8]
  [16 15 12 11  6]]]


In [22]:
# Slicing a 1 D array
print(f"Sliced 1D array : {array_int_1D[3:]}")
print(f"Every second element of the 1D array: {array_int_1D[::2]}")
print(f"every second element from index 3, reversed : {array_int_1D[3::-2]}")

# Slicing a 2 D array - Multidimensional Subarrays 
print(f"First 2 rows and 3 columns:\n{array_int_2D[:2, :3]}")
print(f"All rows and every second column:\n {array_int_2D[:, ::2]}")
print(f"Rows ordering reversed(i.e. last row becomes the first row and so on):\n{array_int_2D[::-1,:]}")
print(f"Columns ordering reversed: \n{array_int_2D[:,::-1]}")
print(f"Both row and column ordering reversed:\n{array_int_2D[::-1,::-1]}")

# Common operations on a 2D array - involves both indexing and slicing 
# The result is a 1D array 
print(f"Second column:\n{array_int_2D[:, 1]}")
print(f"Second row:\n{array_int_2D[1,:]}")

Sliced 1D array : [ 7  7 15]
Every second element of the 1D array: [4 8 7]
every second element from index 3, reversed : [7 5]
First 2 rows and 3 columns:
[[ 3 15 17]
 [ 6  7 10]]
All rows and every second column:
 [[ 3 17 10]
 [ 6 10  2]
 [ 3  7 12]
 [19  5 14]]
Rows ordering reversed(i.e. last row becomes the first row and so on):
[[19 16  5 12 14]
 [ 3 10  7 15 12]
 [ 6  7 10  5  2]
 [ 3 15 17  2 10]]
Columns ordering reversed: 
[[10  2 17 15  3]
 [ 2  5 10  7  6]
 [12 15  7 10  3]
 [14 12  5 16 19]]
Both row and column ordering reversed:
[[14 12  5 16 19]
 [12 15  7 10  3]
 [ 2  5 10  7  6]
 [10  2 17 15  3]]
Second column:
[15  7 10 16]
Second row:
[ 6  7 10  5  2]


**NOTE**

Unlike the Python list slices, NumPy array slices are returned as ***VIEWS*** rather than ***COPIES*** of the array data. Thus, any change made to the view, also impacts the original data.

In [23]:
# Illustration of the above point 
# Consider the 2 D array we are dealing with 
print(array_int_2D)

[[ 3 15 17  2 10]
 [ 6  7 10  5  2]
 [ 3 10  7 15 12]
 [19 16  5 12 14]]


In [24]:
# let us slice this 2 D array and make another subarray
subarray_int_2D = array_int_2D[:2, :2]
print(f"Sliced Subarray:\n{subarray_int_2D}")

# let us change the first element of the subarray to 100
subarray_int_2D[0,0] = 100
print(f"Sliced Subarray after modification:\n{subarray_int_2D}")

# Let us see the original array now!
print(f"Original array has changed too!:\n{array_int_2D}")

Sliced Subarray:
[[ 3 15]
 [ 6  7]]
Sliced Subarray after modification:
[[100  15]
 [  6   7]]
Original array has changed too!:
[[100  15  17   2  10]
 [  6   7  10   5   2]
 [  3  10   7  15  12]
 [ 19  16   5  12  14]]


**✨ What is Fancy Slicing in NumPy?**

- In NumPy, Fancy Slicing (or Fancy Indexing) means accessing elements using arrays (or lists) of indices, instead of using just a range or slice.

- It gives you more flexibility — like picking out specific elements, rows, or columns in any order you want.



In [40]:
# BUT let us now do a fancy slicing 
# let us slice this 2 D array and make another subarray
subarray_int_2D = array_int_2D[[1,3], :]
print(f"Sliced Subarray:\n{subarray_int_2D}")

# let us change the (0,1) element of the subarray to 100
subarray_int_2D[0,1] = 100
print(f"Sliced Subarray after modification:\n{subarray_int_2D}")

# Let us see the original array now!
print(f"The array has not changed:\n{array_int_2D}")

Sliced Subarray:
[[ 6  7 10  5  2]
 [19 16  5 12 14]]
Sliced Subarray after modification:
[[  6 100  10   5   2]
 [ 19  16   5  12  14]]
The array has not changed:
[[100  15  17   2  10]
 [  6   7  10   5   2]
 [  3  10   7  15  12]
 [ 19  16   5  12  14]]


**Key Difference**
- Simple slicing (like `array_int_2D[:2, :2]`) produces a **view**.
- Fancy indexing (like `array_int_2D[[1, 3], :]`) produces a **copy**.

In [41]:
# We can, however, use the copy() method to deliberately create a copy in case of slicing

# let us slice this 2 D array and make another subarray
subarray_int_2D = array_int_2D[:2, :2].copy()
print(f"Sliced Subarray:\n{subarray_int_2D}")

# let us change the first element of the subarray to 100
subarray_int_2D[0,0] = 200
print(f"Sliced Subarray after modification:\n{subarray_int_2D}")

# Let us see the original array now!
print(f"Array has not changed:\n{array_int_2D}")

Sliced Subarray:
[[100  15]
 [  6   7]]
Sliced Subarray after modification:
[[200  15]
 [  6   7]]
Array has not changed:
[[100  15  17   2  10]
 [  6   7  10   5   2]
 [  3  10   7  15  12]
 [ 19  16   5  12  14]]


## D. Reshaping Arrays 

In [42]:
# Let us convert a 1 D array by reshaping it to a 2 D array 
array_1D = np.linspace(start=2, stop=20, num=9)
print(f"Original 1 D array: \n{array_1D}")

array_1D_reshape_2D = array_1D.reshape((3,3))
print(f"The 1 D array after being reshaped to a 2 D array:\n{array_1D_reshape_2D}")

Original 1 D array: 
[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]
The 1 D array after being reshaped to a 2 D array:
[[ 2.    4.25  6.5 ]
 [ 8.75 11.   13.25]
 [15.5  17.75 20.  ]]


In [43]:
# Often we convert 1 D array into a 2 D row or a column matrix
print(f"Original 1 D array: \n{array_1D}")

# reshaping the 1 D to a row vector 
array_1D_rowvec = array_1D.reshape((1,9))
print('Row Vector:')
print(array_1D_rowvec)

# reshaping the 1 D to a column vector 
array_1D_colvec = array_1D.reshape((9,1))
print('Column Vector:')
print(array_1D_colvec)

Original 1 D array: 
[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]
Row Vector:
[[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]]
Column Vector:
[[ 2.  ]
 [ 4.25]
 [ 6.5 ]
 [ 8.75]
 [11.  ]
 [13.25]
 [15.5 ]
 [17.75]
 [20.  ]]


There is an alternate way to acieve the same result! Here we will use the `np.newaxis`

In [44]:
# Often we convert 1 D array into a 2 D row or a column matrix
print(f"Original 1 D array: \n{array_1D}")

# reshaping the 1 D to a row vector 
array_1D_rowvec = array_1D[np.newaxis,:]
print('Row Vector:')
print(array_1D_rowvec)

# reshaping the 1 D to a column vector 
array_1D_colvec = array_1D[:, np.newaxis]
print('Column Vector:')
print(array_1D_colvec)

Original 1 D array: 
[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]
Row Vector:
[[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]]
Column Vector:
[[ 2.  ]
 [ 4.25]
 [ 6.5 ]
 [ 8.75]
 [11.  ]
 [13.25]
 [15.5 ]
 [17.75]
 [20.  ]]


## E. Concatenating two arrays

#### 🧠 Thumb Rule for axis in NumPy
- `axis=0` (Vertical): Rows add up — columns must match
- `axis=1` (Horizontal): Columns add up — rows must match

In [ ]:
# concatenating three 1 D arrays 
array_1 = np.array([1,2,3]) 
array_2 = np.array([4,5,6])
array_3 = np.array([7,8,9])

array_concat = np.concatenate([array_1, array_2, array_3]) # note pass the three arrays in a list
print(array_concat)

[1 2 3 4 5 6 7 8 9]


In [47]:
# Vertical concatenate 
a = np.array([[1, 2],
              [3, 4]]) # (2,2)

b = np.array([[5, 6]]) # (1,2) i.e the columns do match

result = np.concatenate((a, b), axis=0)
result

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
# horixontal concatenate 
a = np.array([[1, 2],
              [3, 4]]) # (2,2)

b = np.array([[5],
              [6]]) # (2,1) - the row dim matches 

result = np.concatenate((a, b), axis=1)
result

array([[1, 2, 5],
       [3, 4, 6]])

So far, we have concatenated the arrays having the same dimensions. However, in reality, it is often the case where the dimensions are not equal. In such cases of **MIXED DIMENSIONS**, one should preferably use `np.hstack` and `np.vstack`

In [ ]:
print(array_1)
print(array_1.shape) # the shape is (3,)

[1 2 3]
(3,)


In [ ]:
array_4 = array_concat.reshape((3,3))
print(array_4)
print(array_4.shape) # (3,3) is the shape 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


So, `array_1` and `array_4` have mixed dimensions. One of the array is a 1D array while the other is a 2D array. 

In [51]:
# vertically stack the array 
np.concatenate([array_1.reshape((1,3)), array_4])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
# horizontally stack 
np.concatenate([array_1.reshape((3,1)), array_4], axis=1)

array([[1, 1, 2, 3],
       [2, 4, 5, 6],
       [3, 7, 8, 9]])

In [53]:
# np.hstack and np.vstack
# say, I want to concatenate array_1 to array_4 row-wise i.e. vertically stack the arrays  
print(np.vstack([array_1, array_4]))

# better reshape the 1D vector to a 2D - makes more sense !
print(np.vstack([array_4,array_1.reshape((1,3))])) # order matters

# Let us now stack horizontally 
# before we stack it horizontally, we need to make it a column vector 
array_5 = array_1.reshape((3,1))
print(np.hstack([array_5, array_4]))

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
[[1 1 2 3]
 [2 4 5 6]
 [3 7 8 9]]


## F. Splitting of the Arrays

In [54]:
# split the array_concat into three different arrays
print(f"The concatenated array: {array_concat}")

arr_split_1, arr_split_2, arr_split_3 = np.split(array_concat, indices_or_sections=[3,6])
print(f"The three splits are: {arr_split_1}, {arr_split_2}, {arr_split_3}")

arr_split_1, arr_split_2, arr_split_3 = np.split(array_concat, indices_or_sections=3)
print(f"The three splits are: {arr_split_1}, {arr_split_2}, {arr_split_3}")

The concatenated array: [1 2 3 4 5 6 7 8 9]
The three splits are: [1 2 3], [4 5 6], [7 8 9]
The three splits are: [1 2 3], [4 5 6], [7 8 9]


Let us now consider a 2D array and split it.

In [57]:
array_concat_row = np.vstack([array_4, array_4])
array_concat_row

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# vertical split 
np.split(array_concat_row, indices_or_sections=2, axis=0)

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])]

In [59]:
# alternate way to split vertically 
np.vsplit(ary=array_concat_row, indices_or_sections=2)

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])]

In [60]:
# split at a particular index 
np.vsplit(ary=array_concat_row, indices_or_sections=[2])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])]

In [62]:
# let us do a horizontal split now 
np.hsplit(ary=array_concat_row, indices_or_sections=[2]) # hsplits at index 2 

[array([[1, 2],
        [4, 5],
        [7, 8],
        [1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9],
        [3],
        [6],
        [9]])]

In [63]:
# alternate way
np.split(array_concat_row, indices_or_sections=[2], axis=1)

[array([[1, 2],
        [4, 5],
        [7, 8],
        [1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9],
        [3],
        [6],
        [9]])]

---

Thank You

---