# NumPy Array Basics

In [5]:
import numpy as np

## Attributes of NumPy Array

In [6]:
# contruct an array
array_int_1D = np.random.randint(low=2, high=20, size=6) # 1 dimensional
array_int_2D = np.random.randint(low=2, high=20, size=(4,5)) # 2 dimensional
array_int_3D = np.random.randint(low=2, high=20, size=(3,4,5)) # 3 dimensional

# accessing the attributes of the array
print(f"The dimensions are : {array_int_1D.ndim}, {array_int_2D.ndim}, {array_int_3D.ndim}") # gives the dimensions of the three arrays
print(f"The shape are : {array_int_1D.shape}, {array_int_2D.shape}, {array_int_3D.shape}") # gives the shape of the arrays 
print(f"The sizes are : {array_int_1D.size}, {array_int_2D.size}, {array_int_3D.size}") # gives the total number of elements in the array
print(f"The datatypes are : {array_int_1D.dtype}, {array_int_2D.dtype}, {array_int_3D.dtype}") # gives the datatype of the elements of the array

The dimensions are : 1, 2, 3
The shape are : (6,), (4, 5), (3, 4, 5)
The sizes are : 6, 20, 60
The datatypes are : int32, int32, int32


## Array Indexing

In [7]:
print(array_int_1D,'\n')
print(array_int_2D,'\n')
print(array_int_3D)

[18 14  5  8 12 16] 

[[ 8  3 12  9  5]
 [ 3 12 13  4  4]
 [ 7 19  9  7  7]
 [13  7  5  7 11]] 

[[[ 5  7 10 14 13]
  [19  4  2  9  3]
  [11 11  7  9 14]
  [ 3 14  6 19 10]]

 [[ 5 12  9 10 11]
  [18 19  9  2  9]
  [ 9 12 19  2 19]
  [15  5  2  6  2]]

 [[12 14 16 14  9]
  [10 14  2 17 12]
  [16 14  7 18  6]
  [11  5  8 17  4]]]


In [8]:
# indexing a 1 D array
print(f'The second element of the 1 D array stated above is : {array_int_1D[1]}')
print(f'The (2,3)th element i.e. the element at the intersection of the second row and the 3rd column is : {array_int_2D[1,2]}')
print(f'The element at (2,3,1)th position is : {array_int_3D[1,2,0]}')

The second element of the 1 D array stated above is : 14
The (2,3)th element i.e. the element at the intersection of the second row and the 3rd column is : 13
The element at (2,3,1)th position is : 9


## Array Slicing

In [9]:
# Slicing a 1 D array 
print(f"Sliced 1 D array : {array_int_1D[3:]}")
print(f"Every second element of the 1 D array: {array_int_1D[::2]}")
print(f"every second element from index 3, reversed : {array_int_1D[3::-2]}")

# Slicing a 2 D array - Multidimensional Subarrays 
print(f"First 2 rows and 3 columns:\n{array_int_2D[:2, :3]}")
print(f"All rows and every second column:\n {array_int_2D[:, ::2]}")
print(f"Rows ordering reversed(i.e. last row becomes the first row and so on):\n{array_int_2D[::-1,:]}")
print(f"Columns ordering reversed: \n{array_int_2D[:,::-1]}")
print(f"Both row and column ordering reversed:\n{array_int_2D[::-1,::-1]}")

# Common operations on a 2 D array - involves both indexing and slicing 
print(f"Second column:\n{array_int_2D[:, 1]}")
print(f"Second row:\n{array_int_2D[1,:]}")

Sliced 1 D array : [ 8 12 16]
Every second element of the 1 D array: [18  5 12]
every second element from index 3, reversed : [ 8 14]
First 2 rows and 3 columns:
[[ 8  3 12]
 [ 3 12 13]]
All rows and every second column:
 [[ 8 12  5]
 [ 3 13  4]
 [ 7  9  7]
 [13  5 11]]
Rows ordering reversed(i.e. last row becomes the first row and so on):
[[13  7  5  7 11]
 [ 7 19  9  7  7]
 [ 3 12 13  4  4]
 [ 8  3 12  9  5]]
Columns ordering reversed: 
[[ 5  9 12  3  8]
 [ 4  4 13 12  3]
 [ 7  7  9 19  7]
 [11  7  5  7 13]]
Both row and column ordering reversed:
[[11  7  5  7 13]
 [ 7  7  9 19  7]
 [ 4  4 13 12  3]
 [ 5  9 12  3  8]]
Second column:
[ 3 12 19  7]
Second row:
[ 3 12 13  4  4]


**NOTE**

Unlike the Python list slices, NumPy array slices are returned as ***VIEWS*** rather than ***COPIES*** of the array data. Thus, any change made to the view, also impacts the original data.

In [22]:
# Illustration of the above point 
# Consider the 2 D array we are dealing with 
print(array_int_2D)

[[100   3  12   9   5]
 [  3  12  13   4   4]
 [  7  19   9   7   7]
 [ 13   7   5   7  11]]


In [23]:
# let us slice this 2 D array and make another subarray
subarray_int_2D = array_int_2D[:2, :2]
print(f"Sliced Subarray:\n{subarray_int_2D}")

# let us change the first element of the subarray to 100
subarray_int_2D[0,0] = 100
print(f"Sliced Subarray after modification:\n{subarray_int_2D}")

# Let us see the original array now!
print(f"Original array has changed too!:\n{array_int_2D}")

Sliced Subarray:
[[100   3]
 [  3  12]]
Sliced Subarray after modification:
[[100   3]
 [  3  12]]
Original array has changed too!:
[[100   3  12   9   5]
 [  3  12  13   4   4]
 [  7  19   9   7   7]
 [ 13   7   5   7  11]]


In [24]:
# BUT let us now do a fancy slicing 
# let us slice this 2 D array and make another subarray
subarray_int_2D = array_int_2D[[1,3], :]
print(f"Sliced Subarray:\n{subarray_int_2D}")

# let us change the (0,1) element of the subarray to 100
subarray_int_2D[0,1] = 100
print(f"Sliced Subarray after modification:\n{subarray_int_2D}")

# Let us see the original array now!
print(f"The array has not changed:\n{array_int_2D}")

Sliced Subarray:
[[ 3 12 13  4  4]
 [13  7  5  7 11]]
Sliced Subarray after modification:
[[  3 100  13   4   4]
 [ 13   7   5   7  11]]
The array has not changed:
[[100   3  12   9   5]
 [  3  12  13   4   4]
 [  7  19   9   7   7]
 [ 13   7   5   7  11]]


**Key Difference**
- Simple slicing (like `array_int_2D[:2, :2]`) produces a **view**.
- Fancy indexing (like `array_int_2D[[1, 3], :]`) produces a **copy**.

In [25]:
# We can, however, use the copy() method to deliberatey create a copy in case of slicing

# let us slice this 2 D array and make another subarray
subarray_int_2D = array_int_2D[:2, :2].copy()
print(f"Sliced Subarray:\n{subarray_int_2D}")

# let us change the first element of the subarray to 100
subarray_int_2D[0,0] = 200
print(f"Sliced Subarray after modification:\n{subarray_int_2D}")

# Let us see the original array now!
print(f"Array has not changed:\n{array_int_2D}")

Sliced Subarray:
[[100   3]
 [  3  12]]
Sliced Subarray after modification:
[[200   3]
 [  3  12]]
Array has not changed:
[[100   3  12   9   5]
 [  3  12  13   4   4]
 [  7  19   9   7   7]
 [ 13   7   5   7  11]]


## Reshaping Arrays 

In [26]:
# Let us convert a 1 D array by reshaping it to a 2 D array 
array_1D = np.linspace(start=2, stop=20, num=9)
print(f"Original 1 D array: \n{array_1D}")

array_1D_reshape_2D = array_1D.reshape((3,3))
print(f"The 1 D array after being reshaped to a 2 D array:\n{array_1D_reshape_2D}")

Original 1 D array: 
[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]
The 1 D array after being reshaped to a 2 D array:
[[ 2.    4.25  6.5 ]
 [ 8.75 11.   13.25]
 [15.5  17.75 20.  ]]


In [27]:
# Often we convert 1 D array into a 2 D row or a column matrix
print(f"Original 1 D array: \n{array_1D}")

# reshaping the 1 D to a row vector 
array_1D_rowvec = array_1D.reshape((1,9))
print('Row Vector:')
print(array_1D_rowvec)

# reshaping the 1 D to a column vector 
array_1D_colvec = array_1D.reshape((9,1))
print('Column Vector:')
print(array_1D_colvec)

Original 1 D array: 
[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]
Row Vector:
[[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]]
Column Vector:
[[ 2.  ]
 [ 4.25]
 [ 6.5 ]
 [ 8.75]
 [11.  ]
 [13.25]
 [15.5 ]
 [17.75]
 [20.  ]]


There is an alternate way to acieve the same result! Here we will use the `np.newaxis`

In [28]:
# Often we convert 1 D array into a 2 D row or a column matrix
print(f"Original 1 D array: \n{array_1D}")

# reshaping the 1 D to a row vector 
array_1D_rowvec = array_1D[np.newaxis,:]
print('Row Vector:')
print(array_1D_rowvec)

# reshaping the 1 D to a column vector 
array_1D_colvec = array_1D[:, np.newaxis]
print('Column Vector:')
print(array_1D_colvec)

Original 1 D array: 
[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]
Row Vector:
[[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]]
Column Vector:
[[ 2.  ]
 [ 4.25]
 [ 6.5 ]
 [ 8.75]
 [11.  ]
 [13.25]
 [15.5 ]
 [17.75]
 [20.  ]]


## Concatenating two arrays

In [29]:
# concatenating three 1 D arrays 
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
array_3 = np.array([7,8,9])

array_concat = np.concatenate([array_1, array_2, array_3]) # note pass the three arrays in a list
print(array_concat)

[1 2 3 4 5 6 7 8 9]


In [30]:
# concatenate 2 D arrays 
array_4 = array_concat.reshape((3,3))
print(array_4)

# say I want to concat the array_4 to itself row-wise i.e. first axis 
array_concat_row = np.concatenate([array_4, array_4])
print(array_concat_row)

# say I want to concat the array_4 to itself column-wise i.e. second axis 
array_concat_col = np.concatenate([array_4, array_4], axis=1)
print(array_concat_col)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


So far, we have concatenated the arrays having the same dimensions. However, in reality, it is often the case where the dimensions are not equal. In such cases of **MIXED DIMENSIONS**, one should preferably use `np.hstack` and `np.vstack`

In [31]:
array_1

array([1, 2, 3])

In [32]:
array_4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
# vertically stack the array 
np.concatenate([array_1.reshape((1,3)), array_4])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
# horizontally stack 
np.concatenate([array_1.reshape((3,1)), array_4], axis=1)

array([[1, 1, 2, 3],
       [2, 4, 5, 6],
       [3, 7, 8, 9]])

In [ ]:
# np.hstack and np.vstack
# say, I want to concatenate array_1 to array_4 row-wise i.e. vertically stack the arrays  
print(np.vstack([array_1, array_4]))

# better reshape the 1D vector to a 2D - makes more sense !
print(np.vstack([array_4,array_1.reshape((1,3))])) # order matters

# Let us now stack horizontally 
# before we stack it horizontally, we need to make it a column vector 
array_5 = array_1.reshape((3,1))
print(np.hstack([array_5, array_4]))

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
[[1 1 2 3]
 [2 4 5 6]
 [3 7 8 9]]


## Splitting of the Arrays

In [20]:
# split the array_concat into three different arrays
print(f"The concatenated array: {array_concat}")

arr_split_1, arr_split_2, arr_split_3 = np.split(array_concat, indices_or_sections=[3,6])
print(f"The three splits are: {arr_split_1}, {arr_split_2}, {arr_split_3}")

arr_split_1, arr_split_2, arr_split_3 = np.split(array_concat, indices_or_sections=3)
print(f"The three splits are: {arr_split_1}, {arr_split_2}, {arr_split_3}")

The concatenated array: [1 2 3 4 5 6 7 8 9]
The three splits are: [1 2 3], [4 5 6], [7 8 9]
The three splits are: [1 2 3], [4 5 6], [7 8 9]


In [44]:
array_concat_row

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Note, earlier I had concatenated array_4 to get array_concat_row - let us split them
print(np.vsplit(ary=array_concat_row, indices_or_sections=2)) # vsplits into 2 arrays
print(np.vsplit(ary=array_concat_row, indices_or_sections=[2])) # vsplits at index 2 

# Note, earlier I had concatenated array_4 to get array_concat_row - let us split them col-wise
print(np.hsplit(ary=array_concat_row, indices_or_sections=[2])) # hsplits at index 2 

[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])]
[array([[1, 2],
       [4, 5],
       [7, 8],
       [1, 2],
       [4, 5],
       [7, 8]]), array([[3],
       [6],
       [9],
       [3],
       [6],
       [9]])]
